apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:

  PORT: "5000"

  MONGODB_URL: "mongodb+srv://<username>:<password>@cluster.mongodb.net/JobPortal"

  JWT_SCRETE_KEY: "secret-key"

  EMAIL_USER: "email@gmail.com"

  EMAIL_PASS: "email-password"

  CLODINARY_NAME: "cloud-name"

  CLODINARY_KEY: "cloud-key"

  CLODINARY_SECRET: "cloud-secret"
